theme: jekyll-theme-minimal
title: U.N. Block0
description: Knowledge Before the Hype  

Blockchain, Web3, and the crypto market explained objectively.  

Web3, DeFi, and crypto without the “get rich while sleeping” talk – because if it were that easy, nobody would work.  

I study before the hype. Trained by top companies and certified in Blockchain by MIT, I bring a technical and strategic perspective on the market.  

Technical analysis and financial markets are part of the game, but without illusions. DYOR always – the market doesn’t forgive the careless.  

A tech and crypto nerd, farming XP in the decentralized world and helping others understand the game.  
